name: Buena Onda Math
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6003373
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00111b'
    - '#d0c2a7'
    - '#3b6365'
    - '#939683'
    - '#006564'
  brandStrength: 0.6875
  lightness: 0.875
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
